# Generated by Django 5.1.3 on 2024-11-08 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilizadores', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='utilizador',
            options={'verbose_name': 'Utilizador'},
        ),
    ]
