# Generated by Django 5.1.3 on 2024-11-14 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilizadores', '0002_alter_utilizador_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='utilizador',
            options={'verbose_name': 'Utilizadore'},
        ),
    ]
