# Generated by Django 5.1.3 on 2024-11-05 17:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0002_alter_livros_co_autor_alter_livros_emprestado_a_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='livros',
            options={'verbose_name': 'Livro'},
        ),
        migrations.RemoveField(
            model_name='livros',
            name='emprestado_data',
        ),
        migrations.RemoveField(
            model_name='livros',
            name='emprestado_data_devolucao',
        ),
        migrations.RemoveField(
            model_name='livros',
            name='emprestado_data_devolucao_real',
        ),
        migrations.AddField(
            model_name='livros',
            name='data_devolucao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livros',
            name='data_emprestimo',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livros',
            name='tempo_duracao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='livros',
            name='data_registo',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
