# Generated by Django 5.1.3 on 2024-11-12 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0004_alter_livros_genero'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livros',
            old_name='titulo',
            new_name='nome',
        ),
    ]
