# Generated by Django 5.1.3 on 2024-11-14 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0005_rename_titulo_livros_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livros',
            name='autor',
            field=models.CharField(max_length=100),
        ),
    ]
