# Generated by Django 5.1.3 on 2024-11-14 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0006_alter_livros_autor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livros',
            name='isbn',
            field=models.CharField(max_length=20),
        ),
    ]
