# Generated by Django 5.1.3 on 2024-11-14 10:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0007_alter_livros_isbn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livros',
            name='ano',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2025)]),
        ),
    ]
