# Generated by Django 5.1.3 on 2024-11-14 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0009_categoria_rename_genero_livros_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livros',
            name='categoria',
            field=models.ForeignKey(choices=[('ficcao', 'Ficção'), ('romance', 'Romance'), ('policial', 'Policial'), ('triller', 'Triller'), ('fantasia', 'Fantasia'), ('autoajuda', 'Autoajuda'), ('biografia', 'Biografia'), ('culinaria', 'Culinária'), ('outros', 'Outros')], on_delete=django.db.models.deletion.DO_NOTHING, to='livro.categoria'),
        ),
    ]
