# Generated by Django 5.1.3 on 2024-11-14 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0010_alter_livros_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='livros',
            name='genero',
            field=models.CharField(choices=[('ficcao', 'Ficção'), ('romance', 'Romance'), ('policial', 'Policial'), ('triller', 'Triller'), ('fantasia', 'Fantasia'), ('autoajuda', 'Autoajuda'), ('biografia', 'Biografia'), ('culinaria', 'Culinária'), ('outros', 'Outros')], default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='livros',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='livro.categoria'),
        ),
    ]
