# Generated by Django 5.1.3 on 2024-11-14 12:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0011_livros_genero_alter_livros_categoria'),
        ('utilizadores', '0004_alter_utilizador_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='livros',
            name='utilizador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='utilizadores.utilizador'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='livros',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='livro.categoria'),
        ),
    ]
