# Generated by Django 5.1.3 on 2024-11-14 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0012_livros_utilizador_alter_livros_categoria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livros',
            name='ano',
            field=models.IntegerField(),
        ),
    ]
