# Generated by Django 5.1.3 on 2024-11-14 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0013_alter_livros_ano'),
    ]

    operations = [
        migrations.RenameField(
            model_name='livros',
            old_name='emprestado_a',
            new_name='nome_emprestado',
        ),
    ]
