# Generated by Django 5.1.3 on 2024-11-14 18:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0014_rename_emprestado_a_livros_nome_emprestado'),
        ('utilizadores', '0004_alter_utilizador_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Livros',
            new_name='Livro',
        ),
    ]
