# Generated by Django 5.1.3 on 2024-11-18 11:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0016_rename_livro_livros'),
        ('utilizadores', '0004_alter_utilizador_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='livros',
            name='genero',
        ),
        migrations.AddField(
            model_name='categoria',
            name='utilizador',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='utilizadores.utilizador'),
            preserve_default=False,
        ),
    ]
