# Generated by Django 5.1.3 on 2024-11-18 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0018_remove_livros_data_devolucao_and_more'),
        ('utilizadores', '0004_alter_utilizador_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emprestimos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_emprestado_anonimo', models.CharField(blank=True, max_length=50, null=True)),
                ('data_emprestimo', models.DateField(blank=True, null=True)),
                ('data_devolucao', models.DateField(blank=True, null=True)),
                ('tempo_duracao', models.DateField(blank=True, null=True)),
                ('livro', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='livro.livros')),
                ('nome_emprestado', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='utilizadores.utilizador')),
            ],
            options={
                'verbose_name': 'Emprestimo',
            },
        ),
        migrations.DeleteModel(
            name='Empréstimos',
        ),
    ]
