# Generated by Django 5.1.3 on 2024-11-18 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0019_emprestimos_delete_empréstimos'),
        ('utilizadores', '0004_alter_utilizador_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimos',
            name='nome_emprestado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='utilizadores.utilizador'),
        ),
    ]
