# Generated by Django 5.1.3 on 2024-11-18 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0020_alter_emprestimos_nome_emprestado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emprestimos',
            name='tempo_duracao',
        ),
    ]
