# Generated by Django 5.1.3 on 2024-11-18 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0022_alter_emprestimos_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emprestimos',
            options={'verbose_name': 'Emprestimo'},
        ),
    ]
