# Generated by Django 5.1.3 on 2024-11-20 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0023_alter_emprestimos_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='emprestimos',
            name='tempo_duracao',
            field=models.DateField(blank=True, null=True),
        ),
    ]
