# Generated by Django 5.1.3 on 2024-11-25 18:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0025_remove_emprestimos_tempo_duracao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emprestimos',
            name='data_emprestimo',
            field=models.DateTimeField(default=datetime.datetime(2024, 11, 25, 18, 20, 41, 57599)),
        ),
    ]
