# Generated by Django 5.1.3 on 2024-12-09 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0037_livros_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livros',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='livros/'),
        ),
    ]
