# Generated by Django 5.1.3 on 2024-12-09 14:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0038_alter_livros_img'),
        ('utilizadores', '0004_alter_utilizador_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livros',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='livro.categoria'),
        ),
        migrations.AlterField(
            model_name='livros',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='capa_livro/'),
        ),
        migrations.AlterField(
            model_name='livros',
            name='utilizador',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='utilizadores.utilizador'),
        ),
    ]
