# Generated by Django 5.1.3 on 2024-12-13 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('livro', '0039_alter_livros_categoria_alter_livros_img_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emprestimos',
            old_name='avalicao',
            new_name='avaliacao',
        ),
    ]
